var biblijaRijeciLako = [
    "Isus",
    "Bog",
    "Marija",
    "Josip",
    "Adam",
    "Eva",
    "Mojsije",
    "Noa",
    "Abraham",
    "David",
    "Salomon",
    "Petar",
    "Pavao",
    "Ivan",
    "Jakov",
    "Juda",
    "anđeo",
    "raj",
    "pakao",
    "nebo",
    "zemlja",
    "potop",
    "Babilon",
    "Egipat",
    "Jeruzalem",
    "Betlehem",
    "križ",
    "uskrsnuće",
    "rođenje",
    "smrt",
    "ljubav",
    "vjera",
    "nada",
    "molitva",
    "greh",
    "oprost",
    "milost",
    "svetost",
    "apostol",
    "prorok",
    "anđeo",
    "đavao",
    "zmija",
    "jabuka",
    "potop svijeta",
    "deset zapovijedi",
    "posljednja večera",
    "raspeće",
    "Golgota",
    "uskrs"
];

var biblijaRijeciSrednje = [
    "stari zavjet",
    "novi zavjet",
    "postanak",
    "knjiga izlaska",
    "evanđelje",
    "otkrivenje",
    "psalmi",
    "mudre izreke",
    "propovjednik",
    "Ivan Krstitelj",
    "Marija Magdalena",
    "Lazar",
    "Judeja",
    "Galileja",
    "Nazaret",
    "Jordan",
    "Sinaj",
    "Crveno more",
    "Arkin zavjet",
    "zlatno tele",
    "Mojsijeva šipka",
    "goriči grm",
    "mana s neba",
    "deset pošasti",
    "prijelaz kroz more",
    "Davidova praćka",
    "Golijat",
    "Salomonov hram",
    "Noina arka",
    "kula babilonska",
    "Sodom i Gomora",
    "tri mudarca",
    "Herodov pokolj",
    "kušnja u pustinji",
    "hod po vodi",
    "promjena vode u vino",
    "umnožavanje kruha",
    "iscjeljenje slijepca",
    "ustajanje mrtvaca",
    "prorok Ilija",
    "prorok Jeremija",
    "prorok Izaija",
    "prorok Daniel",
    "lavlja jama",
    "Samsona i Delila",
    "Ruta i Noemi",
    "Jona i kit",
    "stabla dobra i zla",
    "vrt Getsemani",
    "trideseti srebrenjaka"
];

var biblijaRijeciTesko = [
    "misli s Gore blaženstava",
    "priča o bludnom sinu",
    "priča o milosrdnom Samarijancu",
    "priča o sijaču",
    "priča o talentima",
    "priča o deset djevica",
    "Abramova žrtva Izaka",
    "Jakovljeva ljestvava",
    "Jakov se bori s anđelom",
    "Mojsijev bakrenač zmij",
    "rascijepanje zavjese hrama",
    "uskrsnuće Lazara",
    "preobraženje na gori Tabor",
    "vaznesenje na nebo",
    "silazak Duha Svetoga",
    "speaking in tongues",
    "darovi Duha Svetoga",
    "plodovi Duha Svetoga",
    "sedam smrtnih grijeha",
    "sedam vrlina",
    "četiri jahača apokalipse",
    "sedam pečata",
    "Babilonska bludnica",
    "zvijer iz mora",
    "broj zvijeri šest šest šest",
    "nova Jeruzalem",
    "Melkisedek",
    "Urim i Tumim",
    "Sanhedrin",
    "farizeji",
    "saduceji",
    "zeloti",
    "eseni",
    "progonstvo u Babilonu",
    "Daniel tumači sanje",
    "pisanje na zidu",
    "Jošua i pad Jerihona",
    "sudac Gideon",
    "sudac Samson",
    "kraljica od Sabe",
    "Nabotov vinograd",
    "Ilija uznesenje na nebu",
    "Elizej i dva medvjeda",
    "Job i njegove nevolje",
    "Ezekijelova viđenja",
    "suha kost oživi",
    "vavilonski toranj jezika",
    "Rahab i uhode",
    "Debora sudac i proročica",
    "Pavlov put u Damask"
];