// Filmovi tema - riječi podijeljene po težini

// LAGANO - osnovni filmski pojmovi i poznati filmovi
var filmoviRijeciLako = [
    "glumac",
    "glumica",
    "redatelj",
    "film",
    "kino",
    "kamera",
    "snimanje",
    "premijera",
    "trailer",
    "akcija",
    "komedija",
    "drama",
    "horor",
    "triler",
    "animacija",
    "Titanic",
    "Avatar",
    "Matrix",
    "Hollywood",
    "Oscar",
    "kokice",
    "platno",
    "3D"
];

// SREDNJE - specifičniji filmski termini i pozicije
var filmoviRijeciSrednje = [
    "scenarij",
    "montaža",
    "zvučni efekti",
    "specijalni efekti",
    "kostimi",
    "šminka",
    "casting",
    "producent",
    "studio",
    "blockbuster",
    "kultni film",
    "znanstvena fantastika",
    "fantazija",
    "dokumentarac",
    "biografski",
    "romantika",
    "avantura",
    "mjuzikl",
    "western",
    "noir",
    "nastavak",
    "trilogija",
    "franšiza",
    "remake",
    "adaptacija",
    "kaskader",
    "statist",
    "glavna uloga",
    "sporedna uloga",
    "kameo",
    "scena",
    "kadar",
    "plan",
    "pozadina",
    "prvi plan",
    "osvjetljenje",
    "kinematografija",
    "soundtrack",
    "titlovi",
    "sinkronizacija",
    "DVD",
    "Blu-ray",
    "streaming",
    "projekcija",
    "IMAX",
    "festival",
    "crveni tepih",
    "kritičar",
    "recenzija",
    "Gospodar prstenova",
    "Ratovi zvijezda",
    "Marvel",
    "James Bond",
    "Indiana Jones"
];

// TEŠKO - tehnički filmski pojmovi i specifični nazivi
var filmoviRijeciTesko = [
    "monolog",
    "dijalog",
    "dizajn zvuka",
    "glazba",
    "tema",
    "Cannes",
    "Berlin",
    "Sundance",
    "Pulska arena",
    "ocjena",
    "box office",
    "proračun",
    "zarada",
    "DC Comics",
    "Kum",
    "Casablanca",
    "Građanin Kane",
    "Vertigo",
    "Psihoza",
    "Jaws",
    "E.T.",
    "Jurassic Park",
    "Inception",
    "Interstellar",
    "Pulp Fiction"
];
