// Filozofija tema - pojmovi podijeljeni po težini
// LAGANO: Opće poznati pojmovi, osnovne kategorije, svakodnevna etika i politika  
// SREDNJE: Specifični pojmovi iz filozofijskih pravaca, latina/grčka terminolofija
// TEŠKO: Autorski pojmovi, uski esoteričan termini, visoko-specijalizirano
// NAPOMENA: Mnogi termini su iz latinskog/grčkog podrijetla i koriste se kao takvi na HRV
// SVE KATEGORIJE SU SORTIRANE ABECEDNO

// LAGANO - opće poznati pojmovi
var filozofijaRijeciLako = [
    "altruizam",
    "argument",
    "autoritet",
    "autorstvo",
    "besmisao",
    "bol",
    "budnost",
    "cilj",
    "dijalog",
    "dilema",
    "disciplina",
    "djelovanje",
    "dobro",
    "društvena odgovornost",
    "društvo",
    "duša",
    "dužnost",
    "egoizam",
    "empatija",
    "estetika",
    "etika",
    "filozofija",
    "gledište",
    "harmonija",
    "hrabrost",
    "ideja",
    "identitet",
    "iluzija",
    "introspekcija",
    "iskrenost",
    "iskustvo",
    "istina",
    "istinitost",
    "izazov",
    "izbor",
    "izdržljivost",
    "jednakost",
    "jezik",
    "kaos",
    "karakter",
    "kazna",
    "koncentracija",
    "konflikt",
    "kraj",
    "kretanje",
    "kritika",
    "krivnja",
    "kultura",
    "laž",
    "ljepota",
    "ljubav",
    "ljudsko dostojanstvo",
    "logika",
    "mana",
    "mirovanje",
    "mit",
    "mišljenje",
    "mogućnost",
    "moral",
    "moralna dilema",
    "moralna odgovornost",
    "moralna odluka",
    "motiv",
    "motivacija",
    "moć",
    "mržnja",
    "mudrost",
    "nagrada",
    "namjera",
    "napor",
    "navika",
    "način života",
    "nepravda",
    "nesklad",
    "neslaganje",
    "nesreća",
    "norma",
    "običaj",
    "obmana",
    "odgovor",
    "odgovornost",
    "odluka",
    "odmor",
    "odnos",
    "odrastanje",
    "odricanje",
    "osjećaj smisla",
    "osoba",
    "osobna sloboda",
    "osobnost",
    "osviještenost",
    "pamćenje",
    "patnja",
    "pažnja",
    "perspektiva",
    "pitanje",
    "pogled na svijet",
    "pogreška",
    "pojedinac",
    "ponašanje",
    "poredak",
    "posljedica",
    "postojanje",
    "potraga za smislom",
    "početak",
    "poštenje",
    "poštovanje",
    "požrtvovnost",
    "pravda",
    "pravednost",
    "pravila",
    "pravilo",
    "pretpostavka",
    "prijateljstvo",
    "priroda",
    "priča",
    "promjena",
    "prostor",
    "prosudba",
    "rad",
    "rasprava",
    "rasuđivanje",
    "ravnoteža",
    "razborit izbor",
    "razboritost",
    "razlika",
    "razlog",
    "razmišljanje",
    "razum",
    "razumijevanje",
    "reakcija",
    "red",
    "riječ",
    "ružnost",
    "samokontrola",
    "samopoimanje",
    "samopouzdanje",
    "samopoštovanje",
    "samorefleksija",
    "samospoznaja",
    "savjest",
    "sebičnost",
    "simbol",
    "sjećanje",
    "sklad",
    "slabost",
    "slaganje",
    "sličnost",
    "sljedbenik",
    "sloboda",
    "slobodno vrijeme",
    "smisao",
    "smislenost",
    "smrt",
    "snaga karaktera",
    "spoznaja",
    "sreća",
    "stav",
    "stil života",
    "strpljenje",
    "stvarnost",
    "sud",
    "sukob",
    "sumnja",
    "suosjećanje",
    "suprotnost",
    "svijest",
    "svijet",
    "svjesnost",
    "svjetonazor",
    "svrha",
    "svrhovitost",
    "tijelo",
    "tradicija",
    "trajanje",
    "tumačenje",
    "um",
    "umjerenost",
    "unutarnja sloboda",
    "unutarnji mir",
    "upornost",
    "utjecaj",
    "uvjerenje",
    "uzrok",
    "učenje",
    "učenje na greškama",
    "užitak",
    "vanjska sloboda",
    "veza",
    "vjera",
    "vlast",
    "volja",
    "vrijednosni sustav",
    "vrijednost",
    "vrijednost života",
    "vrijednovanje",
    "vrijeme",
    "vrlina",
    "zabluda",
    "zadovoljstvo",
    "zajednica",
    "zaključak",
    "zakon",
    "zbilja",
    "zlo",
    "znanje",
    "značenje",
    "zrelost",
    "činjenica",
    "čovjek",
    "želja",
    "život",
    "životna iskustva",
    "životna mudrost",
    "životna svrha",
    "životni cilj",
    "životni put",
    "žrtva",

    // RAZDOBLJA FILOZOFIJE

    "analitička filozofija",
    "antička filozofija",
    "arapsko-islamska filozofija",
    "egzistencijalizam",
    "empirizam novog vijeka",
    "fenomenologija",
    "filozofija 20. stoljeća",
    "filozofija 21. stoljeća",
    "filozofija života",
    "frankfurtska škola",
    "helenistička filozofija",
    "hermeneutika",
    "humanizam",
    "kasna skolastika",
    "klasična grčka filozofija",
    "kontinentalna filozofija",
    "kritička teorija",
    "marksizam",
    "njemački idealizam",
    "novovjekovna filozofija",
    "patristika",
    "postmoderna filozofija",
    "postmodernizam",
    "postsekularna filozofija",
    "poststrukturalizam",
    "pozitivizam",
    "pragmatizam",
    "predsokratsko razdoblje",
    "prosvjetiteljstvo",
    "racionalizam novog vijeka",
    "ranokršćanska filozofija",
    "renesansna filozofija",
    "rimska filozofija",
    "romantizam",
    "sekularna filozofija",
    "skolastika",
    "srednjovjekovna filozofija",
    "strukturalizam",
    "suvremena filozofija",
    "transcendentalna filozofija",
    "visoka skolastika",
    "židovska srednjovjekovna filozofija"
];

// SREDNJE - pojmovi iz filozofijskih pravaca
var filozofijaRijeciSrednje = [
    "a posteriori",
    "a priori",
    "afirmacija",
    "akcidens",
    "aksiologija",
    "aktualnost",
    "analitička filozofija",
    "analiza jezika",
    "analogija",
    "anarhizam",
    "antinomija",
    "apsolutni duh",
    "apsurd",
    "arché",
    "areté",
    "argumentacija",
    "aristotelizam",
    "ataraksija",
    "autentično postojanje",
    "autonomija subjekta",
    "baza",
    "bačenost",
    "biopolitika",
    "bit",
    "bitak",
    "briga",
    "cogito",
    "dedukcija",
    "demokracija",
    "deontologija",
    "deterministički svjetonazor",
    "dijalektika",
    "dijalektički proces",
    "diskurs",
    "diskurzivna praksa",
    "doxa",
    "društvena moć",
    "društvena praksa",
    "društvena svijest",
    "društveni ugovor",
    "dualizam",
    "duh vremena",
    "egzistencija",
    "egzistencijalizam",
    "egzistencijalna filozofija",
    "egzistencijalna tjeskoba",
    "empirizam",
    "epikurejstvo",
    "episteme",
    "epistemologija",
    "epistemološki realizam",
    "epistemološki relativizam",
    "esencija",
    "esencijalizam",
    "estetika",
    "etika vrlina",
    "eudaimonija",
    "fenomen",
    "fenomenologija",
    "filozofija jezika",
    "filozofija povijesti",
    "filozofija znanosti",
    "filozofski optimizam",
    "filozofski pesimizam",
    "forma",
    "formalni jezik",
    "genealogija",
    "granice spoznaje",
    "hermeneutika",
    "hipoteza",
    "historicizam",
    "humanizam",
    "idealizam",
    "identitet",
    "imanencija",
    "imanentno",
    "indeterminizam",
    "indukcija",
    "instrumentalni razum",
    "intencionalni akt",
    "intencionalnost",
    "interpretacija",
    "intersubjektivnost",
    "iskustvena spoznaja",
    "istinosna vrijednost",
    "javna sfera",
    "jezična igra",
    "kategorija",
    "kauzalni lanac",
    "kauzalnost",
    "koherencija",
    "konačnost",
    "kontemplacija",
    "kontinentalna filozofija",
    "kontingencija",
    "kontraktualizam",
    "konvencionalizam",
    "konzervativizam",
    "korespondencija",
    "kriticizam",
    "kritika ideologije",
    "kritika racionalnosti",
    "kritika uma",
    "legitimitet",
    "liberalizam",
    "logička valjanost",
    "logički empirizam",
    "logos",
    "materija",
    "materijalizam",
    "materijalni uvjeti",
    "metaetika",
    "metafizika",
    "metodološki skepticizam",
    "modalnost",
    "mogućnost",
    "monade",
    "monizam",
    "moralni realizam",
    "moralni relativizam",
    "moć znanja",
    "nadgradnja",
    "napredak povijesti",
    "naturalizam",
    "neautentično postojanje",
    "negacija",
    "neopozitivizam",
    "nihilizam",
    "nominalizam",
    "normalizacija",
    "normativna etika",
    "normativni sud",
    "noumen",
    "nous",
    "nužnost",
    "objekt",
    "objekt spoznaje",
    "objektivni duh",
    "objektivnost",
    "odgovornost subjekta",
    "odgovornost za izbor",
    "ontičko",
    "ontologija",
    "ontološka razlika",
    "ontološko",
    "osjetilna spoznaja",
    "otuđenje",
    "otuđenje čovjeka",
    "panpsihizam",
    "paradoks",
    "percepcija",
    "personalizam",
    "phronesis",
    "platonizam",
    "pluralizam",
    "pobuna",
    "poiesis",
    "pojmovno mišljenje",
    "politička filozofija",
    "politička ideologija",
    "poststrukturalizam",
    "potencijalnost",
    "povijesna svijest",
    "pozitivizam",
    "pozitivno pravo",
    "pragmatizam",
    "pragmatička istina",
    "praksis",
    "praktični um",
    "pravna država",
    "praxis",
    "predodžba",
    "primijenjena etika",
    "prirodni jezik",
    "prirodno pravo",
    "privatna sfera",
    "protuslovlje",
    "racionalizacija",
    "racionalizam",
    "rad kao samopotvrda",
    "razumska spoznaja",
    "razvoj pojma",
    "realizam",
    "relativizam",
    "republikanizam",
    "res cogitans",
    "res extensa",
    "samootuđenje",
    "samoreferencijalnost",
    "simbolička logika",
    "skepticizam",
    "sloboda izbora",
    "slobodna volja",
    "smisao egzistencije",
    "smrtnost",
    "socijalizam",
    "sofizam",
    "stoicizam",
    "struktura društva",
    "strukturalizam",
    "subjekt",
    "subjekt spoznaje",
    "subjektivacija",
    "subjektivni duh",
    "subjektivnost",
    "sud",
    "supstancija",
    "suverenitet",
    "svijest o sebi",
    "svijet-života",
    "tabula rasa",
    "tehnika",
    "tehnologija",
    "teleologija",
    "teleološko objašnjenje",
    "telos",
    "teorija",
    "teorijski um",
    "transcendencija",
    "transcendentalna filozofija",
    "transcendentalno",
    "utilitarizam",
    "utopija",
    "uvjeti mogućnosti",
    "vrijednosni sud",
    "zaključivanje",
    "značenje riječi",
    "značenjski kontekst",
    "čisti um",

    // ISTOČNA FILOZOFIJA

    "advaita vedanta",
    "ahimsa",
    "anatta",
    "anicca",
    "atman",
    "bodhisattva",
    "brahman",
    "budistička filozofija",
    "dao",
    "daoizam",
    "dharma",
    "dukkha",
    "harmonija",
    "hinduistička filozofija",
    "indijska filozofija",
    "istočna filozofija",
    "japanska filozofija",
    "karma",
    "kineska filozofija",
    "konfucijanizam",
    "kontemplacija",
    "li",
    "mahajana",
    "maya",
    "meditacija",
    "mimamsa",
    "mokša",
    "ne-djelovanje",
    "nirvana",
    "nyaya",
    "osmerostruki put",
    "praznina",
    "prirodni poredak",
    "prosvjetljenje",
    "qi",
    "ravnoteža",
    "samkhya",
    "samsara",
    "srednji put",
    "sunyata",
    "taoizam",
    "theravada",
    "unutarnji mir",
    "vaisheshika",
    "vedanta",
    "wu wei",
    "yin i yang",
    "yoga filozofija",
    "zen",
    "zen-budizam",
    "četiri plemenite istine"
];

// TEŠKO - autorski pojmovi i esoteričan termini
var filozofijaRijeciTesko = [
    "accidens",
    "actus",
    "actus cognitionis",
    "actus hominis",
    "actus humanus",
    "actus purus",
    "adaequatio intellectus et rei",
    "akcidens",
    "analitički sud",
    "analogia entis",
    "antinomija",
    "aporija",
    "aposteriori",
    "apriori",
    "arheologija znanja",
    "ateistički naturalizam",
    "biomoć",
    "biopolitika",
    "bitak",
    "bonum commune",
    "causa efficiens",
    "causa finalis",
    "causa formalis",
    "causa materialis",
    "causa sui",
    "conclusio",
    "contingentia",
    "creatio ex nihilo",
    "decentrirani subjekt",
    "deflacijska teorija istine",
    "dekonstrukcija",
    "demonstratio",
    "denotacija",
    "deontička logika",
    "deteritorijalizacija",
    "determiniranost",
    "dialetheia",
    "diferanca",
    "diskurzivna formacija",
    "događaj",
    "drugi",
    "egzistencija",
    "eidetska redukcija",
    "eliminativni materijalizam",
    "emergencija",
    "ens",
    "ens commune",
    "ens per accidens",
    "ens per se",
    "entelehija",
    "epifenomenalizam",
    "episteme",
    "epistemička logika",
    "epistemološka opravdanost",
    "epistemološki eksternalizam",
    "epistemološki fundacionalizam",
    "epistemološki infinitizam",
    "epistemološki internalizam",
    "epistemološki koherentizam",
    "esencija",
    "esse",
    "essentia",
    "fatalizam",
    "fenomenalno",
    "fenomenološka redukcija",
    "filozofija običnog jezika",
    "filozofski skepticizam",
    "forma substantialis",
    "fragmentacija subjekta",
    "funkcionalizam",
    "genealogija morala",
    "Gettierov problem",
    "govorni čin",
    "haecceitas",
    "hegemonija",
    "hermeneutički krug",
    "hiperrealnost",
    "hipotetički imperativ",
    "identitas indiscernibilium",
    "identitet kroz promjenu",
    "identitet uma i tijela",
    "ideološki aparat",
    "ilokucija",
    "imaginarno",
    "imanentno",
    "inkompatibilizam",
    "intellectus",
    "intellectus agens",
    "intellectus possibilis",
    "intencionalnost svijesti",
    "intentio",
    "intertekstualnost",
    "intuicionistička logika",
    "istinosni uvjeti",
    "jezična referencija",
    "jezični obrat",
    "justifikacija",
    "kategorički imperativ",
    "kauzalitet",
    "koherentna teorija istine",
    "kompatibilizam",
    "konceptualizam",
    "konceptualna analiza",
    "konotacija",
    "kontingencija",
    "kontingentni sud",
    "korespondencijska teorija istine",
    "kozmološki argument",
    "lažna svijest",
    "lex naturalis",
    "lex positiva",
    "libertarijanizam",
    "logička forma",
    "logička struktura",
    "materia prima",
    "metafizički antirealizam",
    "metafizički realizam",
    "metanarativ",
    "modalitet",
    "modalna logika",
    "modus ponens",
    "modus tollens",
    "mogući svjetovi",
    "monade",
    "moć-znanje",
    "moždani u posudi",
    "naturalistički teizam",
    "naturalizirana epistemologija",
    "necessitas",
    "nedostatak",
    "ništa",
    "noema",
    "noesis",
    "nominalizam univerzalija",
    "normalizacija",
    "noumenalno",
    "nužni sud",
    "nužnost",
    "objectum formale",
    "ontičko",
    "ontološka diferencija",
    "ontološka interpretacija",
    "ontološki argument",
    "ontološki emergentizam",
    "ontološki konstruktivizam",
    "ontološki nominalizam",
    "ontološki pluralizam",
    "ontološki realizam",
    "ontološki redukcionizam",
    "ontološko",
    "ontoteologija",
    "ordo",
    "panlogizam",
    "panpsihizam",
    "parakonzistentna logika",
    "participatio",
    "performativ",
    "perlokucija",
    "persona",
    "pisanje",
    "postmoderna",
    "postsekularizam",
    "potentia",
    "praemissa",
    "praktički um",
    "predrazumijevanje",
    "predustanovljena harmonija",
    "princip identiteta",
    "princip isključenog trećeg",
    "princip neprotuslovlja",
    "principium causalitatis",
    "principium individuationis",
    "principium rationis sufficientis",
    "problem identiteta",
    "problem individue",
    "problem slobodne volje",
    "problem svijesti",
    "problem uma i tijela",
    "problem univerzalija",
    "problem zla",
    "qualia",
    "quidditas",
    "ratio",
    "razlika",
    "realizam univerzalija",
    "realno",
    "redukcija",
    "referencijalna teorija značenja",
    "religijska epistemologija",
    "reteritorijalizacija",
    "rizomska struktura",
    "sapientia",
    "scientia",
    "sekularizacija",
    "simbolički poredak",
    "simulakrum",
    "sintetički sud",
    "skeptički paradoks",
    "slobodna volja",
    "species intelligibilis",
    "species sensibilis",
    "subjekt bez supstancije",
    "subjektivacija",
    "substantia",
    "sufficient reason",
    "summum bonum",
    "supervenijencija",
    "suppositum",
    "supstancija",
    "svijest o sebi",
    "svijet-života",
    "syllogismus",
    "synderesis",
    "tekstualnost",
    "teleologia",
    "teleologizam",
    "teleološki argument",
    "temporalna logika",
    "teodiceja",
    "teorija istine",
    "teorijski um",
    "trace",
    "transcendentalna apercepcija",
    "transcendentalno",
    "transcendentno",
    "universalia",
    "uporabna teorija značenja",
    "velike priče",
    "veritas",
    "viševrijednosna logika",
    "volja",
    "zli demon",
    "znanje kao opravdano istinito vjerovanje",
    "čisti um",
    "želja"
];
