// Geografija tema - riječi podijeljene po težini

// LAGANO - poznate države, gradovi i osnovni geografski pojmovi
var geografijaRijeciLako = [
    "Zagreb",
    "Split",
    "Rijeka",
    "Dubrovnik",
    "Hrvatska",
    "Slovenija",
    "Italija",
    "Njemačka",
    "Francuska",
    "Španjolska",
    "Engleska",
    "Amerika",
    "Kanada",
    "Brazil",
    "Kina",
    "Japan",
    "Australija",
    "planina",
    "brdo",
    "rijeka",
    "jezero",
    "more",
    "ocean",
    "otok",
    "šuma",
    "pustinja",
    "plaža",
    "grad",
    "selo",
    "Europa",
    "Azija",
    "Afrika",
    "sjever",
    "jug",
    "istok",
    "zapad"
];

// SREDNJE - specifičnije lokacije i geografski termini
var geografijaRijeciSrednje = [
    "Osijek",
    "Zadar",
    "Pula",
    "Slavonija",
    "Dalmacija",
    "Istra",
    "Lika",
    "Gorski Kotar",
    "Međimurje",
    "Bosna i Hercegovina",
    "Srbija",
    "Crna Gora",
    "Makedonija",
    "Austrija",
    "Mađarska",
    "Portugal",
    "Škotska",
    "Wales",
    "Irska",
    "Belgija",
    "Nizozemska",
    "Švicarska",
    "Norveška",
    "Švedska",
    "Finska",
    "Danska",
    "Island",
    "Rusija",
    "Ukrajina",
    "Poljska",
    "Češka",
    "Slovačka",
    "Rumunjska",
    "Bugarska",
    "Grčka",
    "Turska",
    "SAD",
    "Meksiko",
    "Argentina",
    "Čile",
    "Peru",
    "Kolumbija",
    "Venezuela",
    "Južna Koreja",
    "Indija",
    "Tajland",
    "Vijetnam",
    "Novi Zeland",
    "Egipat",
    "Maroko",
    "Južnoafrička Republika",
    "Kenija",
    "dolina",
    "kanjon",
    "spilja",
    "zaljev",
    "uvala",
    "poluotok",
    "arhipelag",
    "džungla",
    "savana",
    "step",
    "tundra",
    "ledenjak",
    "vulkan",
    "gejzir",
    "vodopad",
    "izvor",
    "ušće",
    "delta",
    "obala",
    "litica",
    "brežuljak",
    "visoravan",
    "ravnica",
    "Alpe",
    "Himalaja",
    "Andi",
    "Dunav",
    "Sava",
    "Drava",
    "Nil",
    "Amazona",
    "Mississippi",
    "Jadransko more",
    "Sredozemno more",
    "Crno more",
    "Atlantski ocean",
    "Tihi ocean",
    "Indijski ocean",
    "Sahara",
    "Antarktika",
    "Arktik",
    "ekvator",
    "kontinent",
    "Oceanija",
    "glavni grad",
    "metropola",
    "regija",
    "pokrajina",
    "država",
    "granica",
    "karta",
    "kompas"
];

// TEŠKO - specifični geografski termini i manje poznate lokacije
var geografijaRijeciTesko = [
    "rت",
    "jarak",
    "Kilimandžaro",
    "Mount Everest",
    "Gobi",
    "Grenland",
    "tropski pojas",
    "polarni krug",
    "polutok",
    "GPS",
    "koordinate",
    "zemljopisna širina",
    "zemljopisna dužina"
];
