// Glazba tema - riječi podijeljene po težini

// LAGANO - osnovni glazbeni instrumenti i pojmovi
var glazbaRijeciLako = [
    "gitara",
    "klavir",
    "bubnjevi",
    "violina",
    "flauta",
    "truba",
    "harmonika",
    "pjesma",
    "pjevanje",
    "bend",
    "koncert",
    "mikrofon",
    "album",
    "rock",
    "pop",
    "jazz",
    "rap",
    "noter",
    "refren",
    "solo",
    "melodija",
    "ritam",
    "tempo"
];

// SREDNJE - specifičniji instrumenti i glazbeni pojmovi
var glazbaRijeciSrednje = [
    "bas",
    "violončelo",
    "viola",
    "kontrabas",
    "klarinet",
    "saksofon",
    "trombon",
    "usna harmonika",
    "tambura",
    "mandolina",
    "banjo",
    "ukulele",
    "orgulje",
    "sintisajzer",
    "činele",
    "hi-hat",
    "tom-tom",
    "marakase",
    "bongo",
    "conga",
    "ksilofon",
    "vibrafon",
    "zvona",
    "triangl",
    "tamburin",
    "električna gitara",
    "akustična gitara",
    "klasična gitara",
    "tonalitet",
    "nota",
    "akord",
    "harmonija",
    "strofa",
    "most",
    "orkestar",
    "zbor",
    "dirigent",
    "turneja",
    "festival",
    "pozornica",
    "pojačalo",
    "zvučnik",
    "singl",
    "vinili",
    "kazeta",
    "CD",
    "streaming",
    "Spotify",
    "blues",
    "klasična glazba",
    "opera",
    "heavy metal",
    "punk",
    "reggae",
    "ska",
    "funk",
    "soul",
    "R&B",
    "hip hop",
    "elektronička glazba",
    "techno",
    "house",
    "country",
    "folk",
    "sevdah",
    "klapa",
    "etno",
    "latino",
    "salsa",
    "samba",
    "tango",
    "valcer",
    "polka"
];

// TEŠKO - specifični termini, glazbeni stilovi i izvođači
var glazbaRijeciTesko = [
    "sitara",
    "EP",
    "LP",
    "trance",
    "dubstep",
    "drum and bass",
    "world music",
    "Beatles",
    "Rolling Stones",
    "Queen",
    "Led Zeppelin",
    "Pink Floyd",
    "Michael Jackson",
    "Madonna",
    "Elvis Presley"
];
