// Hrana tema - riječi podijeljene po težini

// LAGANO - osnovna hrana i jela
var hranaRijeciLako = [
    "pizza",
    "hamburger",
    "sendvič",
    "salata",
    "juha",
    "kruh",
    "krumpir",
    "pomfrit",
    "tjestenina",
    "špageti",
    "riba",
    "piletina",
    "kobasica",
    "doručak",
    "ručak",
    "večera",
    "desert",
    "torta",
    "kolač",
    "čokolada",
    "sladoled",
    "voće",
    "jabuka",
    "banana",
    "naranča",
    "jagoda",
    "grožđe",
    "lubenica",
    "povrće",
    "rajčica",
    "krastavac",
    "paprika",
    "luk",
    "mrkva",
    "sir",
    "mlijeko",
    "jaje",
    "voda",
    "sok"
];

// SREDNJE - specifičnija jela i namirnice
var hranaRijeciSrednje = [
    "čorba",
    "grah",
    "goulash",
    "sarma",
    "punjene paprike",
    "ćevapi",
    "pljeskavica",
    "raznjići",
    "šnicla",
    "odrezak",
    "pečenje",
    "rižoto",
    "palenta",
    "pire",
    "pečeni krumpir",
    "lazanje",
    "carbonara",
    "bolognese",
    "pesto",
    "tuna",
    "losos",
    "pastrva",
    "srdela",
    "školjke",
    "lignje",
    "hobotnica",
    "rakovi",
    "jastog",
    "škampi",
    "sushi",
    "purica",
    "patka",
    "govedina",
    "svinjetina",
    "janjetina",
    "salama",
    "pršut",
    "panceta",
    "užina",
    "predjelo",
    "glavno jelo",
    "prilog",
    "umak",
    "začini",
    "sol",
    "papar",
    "šećer",
    "ulje",
    "ocat",
    "senf",
    "kečap",
    "majoneza",
    "keks",
    "puding",
    "palačinke",
    "muffin",
    "kroasan",
    "štrudla",
    "baklava",
    "krempita",
    "tiramisu",
    "cheesecake",
    "brownie",
    "limun",
    "maline",
    "borovnice",
    "kruška",
    "breskva",
    "šljiva",
    "dinja",
    "ananas",
    "mango",
    "kivi",
    "salata",
    "češnjak",
    "kelj",
    "kupus",
    "brokula",
    "karfiol",
    "tikvica",
    "patlidžan",
    "gljive",
    "šampinjoni",
    "mozzarella",
    "parmezan",
    "cheddar",
    "jogurt",
    "maslac",
    "omlet",
    "kajgana",
    "pecivo",
    "žemlja"
];

// TEŠKO - specifični nazivi i egzotična hrana
var hranaRijeciTesko = [
    "brie",
    "cottage cheese",
    "vrhnje",
    "pavlaka",
    "tvrdo kuhano jaje",
    "lepinja",
    "bagel",
    "toast"
];
