// ============================================
// KLASIČNA GLAZBA - STRUČNI TERMINI
// ============================================

// 1. SKLADATELJI
var klasicnaGlazbaLako = [

// 1. SKLADATELJI
    "Antonio Vivaldi",
    "Claude Debussy",
    "Frédéric Chopin",
    "Franz Schubert",
    "George Frideric Handel",
    "Giuseppe Verdi",
    "Gustav Mahler",
    "Igor Stravinsky",
    "Johann Sebastian Bach",
    "Johannes Brahms",
    "Ludwig van Beethoven",
    "Maurice Ravel",
    "Pyotr Ilyich Tchaikovsky",
    "Richard Wagner",
    "Sergei Rachmaninoff",
    "Wolfgang Amadeus Mozart",

// 2. OPERE
    "Aida",
    "Carmen",
    "Così fan tutte",
    "Die Zauberflöte",
    "Don Giovanni",
    "Fidelio",
    "Il barbiere di Siviglia",
    "La bohème",
    "La traviata",
    "Le nozze di Figaro",
    "Madama Butterfly",
    "Rigoletto",
    "Tosca",
    "Turandot",

// 3. SOLFEGGIO
    "Alteracija",
    "Cijeli stepen",
    "Dijatonika",
    "Dominanta",
    "Durska ljestvica",
    "Intonacija",
    "Interval",
    "Intervali",
    "Kadenca",
    "Kvarta",
    "Kvinta",
    "Medijanta",
    "Molska ljestvica",
    "Oktava",
    "Polustepen",
    "Seksta",
    "Sekunda",
    "Septima",
    "Subdominanta",
    "Terca",
    "Tonalitet",
    "Tonika",

// 4. NOTNE VRIJEDNOSTI
    "2/4 takt",
    "3/4 takt",
    "4/4 takt",
    "6/8 takt",
    "Binarna mjera",
    "Cijela nota",
    "Cijela pauza",
    "Četvrtinka",
    "Četvrtinska pauza",
    "Osminka",
    "Osminska pauza",
    "Polovinka",
    "Polovinska pauza",
    "Jednostavna mjera",
    "Punktirana četvrtinka",
    "Punktirana osminka",
    "Punktirana polovinka",
    "Složena mjera",
    "Takt",
    "Trodobna mjera",
    "Triola",
    "Šesnaestinka",
    "Šesnaestinka pauza",
    "Tridesetdruginka",
    "Tridesetdruginska pauza",
    "Šezdesetčetvrtinka",
    "Šezdesetčetvrtinska pauza",

// 5. ARTIKULACIJE
    "Acciaccatura",
    "Appoggiatura",
    "Arco",
    "Col legno",
    "Con sordino",
    "Glissando",
    "Gruppetto",
    "Legato",
    "Marcato",
    "Mordent",
    "Non vibrato",
    "Pizzicato",
    "Portamento",
    "Senza sordino",
    "Staccato",
    "Sul ponticello",
    "Sul tasto",
    "Tenuto",
    "Tremolo",
    "Trillo",
    "Vibrato",

// 6. ORKESTRACIJA
    "Arco tutti",
    "Fanfare",
    "Limeni puhači",
    "Colla parte",
    "Concertino",
    "Divisi",
    "Doubling",
    "Gudači kvartet",
    "Komorni sastav",
    "Muted brass",
    "Octave doubling",
    "Percussion ensemble",
    "Ripieno",
    "Simfonijski orkestar",
    "Solo dionice",
    "String soli",
    "Tutti",
    "Tutti unison",
    "Unison doubling",
    "Wind soli",
    "Woodwind chorale",
    "Drveni puhači",

// 7. INSTRUMENTI
    "Bas bubanj",
    "Celestas",
    "Doboš",
    "Fagot",
    "Flauta",
    "Gitara",
    "Harfa",
    "Klarinet",
    "Klavir",
    "Kontrabas",
    "Marimba",
    "Oboa",
    "Orgulje",
    "Timpani",
    "Triangl",
    "Trombon",
    "Truba",
    "Tuba",
    "Vibrafon",
    "Viola",
    "Violina",
    "Violončelo",
    "Ksilofon",
    "Činele",
    "Čembalo",


// 8. GLAZBENI OBLICI
    "Allemande",
    "Aria",
    "Balada",
    "Bourree",
    "Canon",
    "Capriccio",
    "Cavatina",
    "Chaconne",
    "Courante",
    "Etida",
    "Fantazija",
    "Fuga",
    "Gavotte",
    "Gigue",
    "Impromptu",
    "Interlude",
    "Intermezzo",
    "Koncert",
    "Lied",
    "March",
    "Mazurka",
    "Menuet",
    "Nokturno",
    "Overture",
    "Partita",
    "Passacaglia",
    "Pastorale",
    "Polonaise",
    "Postlude",
    "Preludij",
    "Recitativ",
    "Rapsodija",
    "Ricercar",
    "Rondo",
    "Sarabande",
    "Scherzo",
    "Simfonija",
    "Sinfonietta",
    "Sonata",
    "Suite",
    "Tema s varijacijama",
    "Toccata",
    "Valcer",

// 9. KOMPOZICIJA - tehnike
    "Binarna forma",
    "Dvoglasna pjesma",
    "Dvostruka ekspozicija",
    "Ekspozicija",
    "Harmonijska progresija",
    "Imitacija",
    "Kanon",
    "Koda",
    "Kontrapunkt",
    "Kontrastni tipovi",
    "Leitmotiv",
    "Melodic doubling",
    "Modulacija",
    "Ostinato",
    "Pedalni ton",
    "Polyphony",
    "Prelaz (bridge)",
    "Razrada motiva",
    "Razvoj teme",
    "Repriza",
    "Rondo",
    "Sekvenca",
    "Slobodna forma",
    "Sonatni oblik",
    "Stretto",
    "Tema s varijacijama",
    "Ternarni oblik",
    "Troglasna pjesma",
    "Through-composed",

// 10. POLIFONIJA / KONTRAPUNKT
    "Cantus firmus",
    "Conducta",
    "Dvoglasni kontrapunkt",
    "Fugato",
    "Fugetta",
    "Imitacijski kontrapunkt",
    "Invencija",
    "Kanonska imitacija",
    "Organum",
    "Slobodni kontrapunkt",
    "Strogi kontrapunkt",
    "Troglasni kontrapunkt",
    "Četveroglasni kontrapunkt",

// 11. HARMONIJA

    "Diminuirani akord",
    "Dominanta",
    "Dominantni septakord",
    "Durski trozvuk",
    "Funkcijska harmonija",
    "Kvartni akord",
    "Kvartsekstakord",
    "Kvintni akord",
    "Mali molski septakord",
    "Molski trozvuk",
    "Nonakord",
    "Osnovni položaj",
    "Povećani kvintakord",
    "Septakord",
    "Sekstakord",
    "Subdominanta",
    "Trozvuk",
    "Tonika",
    "Smanjeni septakord",
    "Veliki durski septakord",

// 12. DIRIGIRANJE
    "2/4 pattern",
    "3/4 pattern",
    "4/4 pattern",
    "6/8 pattern",
    "Accelerando gesture",
    "Beat pattern",
    "Baton technique",
    "Body language",
    "Breathing indication",
    "Cue (znak)",
    "Cut-off",
    "Downbeat",
    "Dynamics shaping",
    "Eye contact",
    "Facial expression",
    "Fermata gesture",
    "Ictus",
    "Left-hand technique",
    "Legato gesture",
    "Marcato gesture",
    "Non-baton conducting",
    "Preparatory beat",
    "Right-hand technique",
    "Ritardando gesture",
    "Rubato direction",
    "Staccato gesture",
    "Subdivizija",
    "Subito changes",
    "Taktiranje",
    "Tempo control",
    "Upbeat",

// 13. ELEKTRONSKA GLAZBA
    "ADSR (Envelope)",
    "Chorus",
    "Compression",
    "Delay",
    "Digital audio workstation",
    "Distortion",
    "Echo",
    "EQ (equalization)",
    "Flanger",
    "Limiting",
    "Loop",
    "MIDI",
    "Oscillator",
    "Overdrive",
    "Panning",
    "Phaser",
    "Reverb",
    "Sampling",
    "Sequencer",
    "Signal processing",

// 14. MUZIKOLOGIJA
    "Analiza glazbe",
    "Atribucija",
    "Autograf",
    "Datiranje",
    "Estetika glazbe",
    "Etnomuzikologija",
    "Filološka analiza",
    "Filozofija glazbe",
    "Formalna analiza",
    "Harmonijska analiza",
    "Historiografija glazbe",
    "Historijski kontekst",
    "Ikonografija",
    "Kritičko izdanje",
    "Manuskripti",
    "Organologija",
    "Paleografija",
    "Performans praksa",
    "Provijencija",
    "Semiologija",
    "Sistematska muzikologija",
    "Skica (sketch)",
    "Stilska analiza",
    "Tablature",
    "Urtext",

// 15. OZNAKE IZVOĐENJA - tempo/karakter
    "A tempo",
    "Accelerando",
    "Ad libitum",
    "Adagio",
    "Adagietto",
    "Affrettando",
    "Agitato",
    "Allegretto",
    "Allegro",
    "Allargando",
    "Andante",
    "Andantino",
    "Appassionato",
    "Brillante",
    "Con brio",
    "Con fuoco",
    "Con moto",
    "Doppio movimento",
    "Energico",
    "Giocoso",
    "Grandioso",
    "Grave",
    "Grazioso",
    "Largo",
    "Larghetto",
    "Leggiero",
    "Lento",
    "L'istesso tempo",
    "Maestoso",
    "Marziale",
    "Meno mosso",
    "Moderato",
    "Pesante",
    "Più mosso",
    "Pomposo",
    "Presto",
    "Prestissimo",
    "Rallentando",
    "Ritardando",
    "Ritenuto",
    "Rubato",
    "Scherzando",
    "Senza tempo",
    "Solenne",
    "Sostenuto",
    "Stringendo",
    "Tempo primo",
    "Tranquillo",
    "Vigoroso",
    "Vivace",

// 16. OZNAKE DINAMIKE
    "Agitato",
    "Appassionato",
    "Calando",
    "Cantabile",
    "Con anima",
    "Con forza",
    "Con grazia",
    "Con spirito",
    "Con tenerezza",
    "Crescendo",
    "Decrescendo",
    "Diminuendo",
    "Dolce",
    "Dolcissimo",
    "Espressivo",
    "Forte (f)",
    "Forte piano (fp)",
    "Fortissimo (ff)",
    "Fortissimo possibile (fff)",
    "Furioso",
    "Maestoso",
    "Marcato",
    "Mezzo forte (mf)",
    "Mezzo piano (mp)",
    "Morendo",
    "Piano (p)",
    "Pianissimo (pp)",
    "Rinforzando (rf/rfz)",
    "Sforzando (sf/sfz)",
    "Smorzando",
    "Sostenuto",
    "Sotto voce",
    "Subito forte",
    "Subito piano",
    "Tranquillo",

// 17. POVIJEST GLAZBE - razdoblja/stilovi
    "Apsolutna glazba",
    "Antička glazba",
    "Ars antiqua",
    "Ars nova",
    "Barok",
    "Bečka klasika",
    "Chanson",
    "Empfindsamer Stil",
    "Galant stil",
    "Gregorijanski koral",
    "Impresionizam",
    "Kantata",
    "Kasni barok",
    "Kasni romantizam",
    "Klasicizam",
    "Madrigal",
    "Magnificat",
    "Misa (Mass)",
    "Motet",
    "Nacionalni stilovi",
    "Oratorij",
    "Pasija",
    "Programska glazba",
    "Puni romantizam",
    "Rani barok",
    "Rani romantizam",
    "Renesansa",
    "Requiem",
    "Romantizam",
    "Stabat Mater",
    "Srednji barok",
    "Srednji vijek",
    "Sturm und Drang",
    "Te Deum"

];



// SREDNJE - Stručniji pojmovi, specifičnije tehnike
var klasicnaGlazbaSrednje = [

// 1. SKLADATELJI
    "Aaron Copland",
    "Alban Berg",
    "Anton Bruckner",
    "Anton Webern",
    "Antonín Dvořák",
    "Arnold Schoenberg",
    "Béla Bartók",
    "Bedřich Smetana",
    "Benjamin Britten",
    "Camille Saint-Saëns",
    "Carl Maria von Weber",
    "Dmitri Shostakovich",
    "Edvard Grieg",
    "Erik Satie",
    "Felix Mendelssohn",
    "Franz Joseph Haydn",
    "Franz Liszt",
    "Gabriel Fauré",
    "Giacomo Puccini",
    "Hector Berlioz",
    "Henry Purcell",
    "Jacopo Peri",
    "Jean Sibelius",
    "Modest Mussorgsky",
    "Robert Schumann",
    "Samuel Barber",

// 1. HRVATSKI SKLADATELJI

    "Adalbert Marković",
    "Albe Vidaković",
    "Aleksandar Ilić",
    "Anđelko Klobučar",
    "Antun Dobronić",
    "Antun Sorkočević",
    "Berislav Šipuš",
    "Blagoje Bersa",
    "Boris Papandopulo",
    "Branimir Sakač",
    "Branko Horvat",
    "Davorin Kempf",
    "Dora Pejačević",
    "Dubravko Detoni",
    "Faust Vrančić",
    "Ferdo Livadić",
    "Fran Đurđevic",
    "Fran Lhotka Kalinski",
    "Frano Parać",
    "Franjo Dugan",
    "Franjo Kuhač",
    "Franjo Lučić",
    "Igor Kuljerić",
    "Ivan Brkljačić",
    "Ivan Brkanović",
    "Ivan Lukačić",
    "Ivan Matetić Ronjgov",
    "Ivan Zajc",
    "Jakov Gotovac",
    "Josip Andreis",
    "Josip Hatze",
    "Josip Kaplan",
    "Josip Magdić",
    "Josip Slavenski",
    "Josip Štolcer Slavenski",
    "Juraj Dobrila",
    "Juraj Fiamengo",
    "Krešimir Baranović",
    "Krsto Odak",
    "Ladislav Šaban",
    "Lovro Županović",
    "Luka Sorkočević",
    "Marij Kogoj",
    "Marijan Gabrijelski",
    "Marko Ruždjak",
    "Milko Kelemen",
    "Milo Cipra",
    "Miro Belamarić",
    "Natko Devčić",
    "Pavao Markovac",
    "Pavle Dešpalj",
    "Petar Bergamo",
    "Rudolf Matz",
    "Silvije Bombardelli",
    "Slavko Osterc",
    "Stanko Horvat",
    "Stjepan Šulek",
    "Vatroslav Lisinski",
    "Vinko Jelić",
    "Vinko Žganec",
    "Želimir Brkanović",



// 2. OPERE
    "Boris Godunov",
    "Cavalleria rusticana",
    "Der fliegende Holländer",
    "Der Rosenkavalier",
    "Die Fledermaus",
    "Die Walküre",
    "Elektra",
    "Eugene Onegin",
    "Götterdämmerung",
    "Hänsel und Gretel",
    "Il trovatore",
    "L'Orfeo",
    "Lohengrin",
    "Norma",
    "Otello",
    "Pagliacci",
    "Parsifal",
    "Pelléas et Mélisande",
    "Salome",
    "Tannhäuser",
    "Tristan und Isolde",
    "Un ballo in maschera",

// 3. SOLFEGGIO
    "Apsolutni sluh",
    "Enharmonija",
    "Fermata",
    "Harmonijska mol ljestvica",
    "Konsonanca",
    "Kromatska ljestvica",
    "Ligatura",
    "Mala tercija",
    "Melodijska linija",
    "Melodijska mol ljestvica",
    "Modulacija",
    "Pentatonika",
    "Povećana kvarta",
    "Prirodna mol ljestvica",
    "Punktirana nota",
    "Razrješenje",
    "Relativni sluh",
    "Sinkopa",
    "Smanjena kvinta",
    "Solmizacija",
    "Tonski centar",
    "Transpozicija",
    "Triola",
    "Vodeći ton",
    "Velika tercija",

// 4. NOTNE VRIJEDNOSTI
    "12/8 takt",
    "5/4 takt",
    "7/8 takt",
    "9/8 takt",
    "Akcent",
    "Alla breve",
    "Anacrusis",
    "Common time (C)",
    "Cross-rhythm",
    "Duola",
    "Dvostruko punktirana nota",
    "Hemiola",
    "Kvintola",
    "Legato",
    "Luk",
    "Međuudar (upbeat)",
    "Metar",
    "Nepravilna mjera",
    "Poliritmija",
    "Punktirana šesnaestinka",
    "Septola",
    "Sekstola",
    "Tridesetdruginka",
    "Tridesetdruginska pauza",
    "Udar (downbeat)",

// 5. ARTIKULACIJE
    "Bartók pizzicato",
    "Col legno battuto",
    "Col legno tratto",
    "Détaché",
    "Double stop",
    "Double tonguing",
    "Flutter tonguing",
    "Frullato",
    "Harmonics (flažoleti)",
    "Jeté",
    "Left-hand pizzicato",
    "Legato tonguing",
    "Louré",
    "Martelé",
    "Open strings",
    "Portato",
    "Quadruple stop",
    "Ricochet",
    "Sautillé",
    "Slap tongue",
    "Spiccato",
    "Staccatissimo",
    "Staccato volant",
    "Stopped horn",
    "Sul G (D, A, E)",
    "Triple stop",
    "Triple tonguing",

// 6. ORKESTRACIJA
    "Antiphonal brass",
    "Col legno sekcija",
    "Density control",
    "Extreme registers",
    "Flutter tongue ensemble",
    "Glissando effect",
    "Harp glissandi",
    "Heterophonic texture",
    "Homophonic texture",
    "Layering",
    "Mixed timbres",
    "Obbligato",
    "Off-stage instruments",
    "Orchestral balance",
    "Orchestral blend",
    "Orchestral color",
    "Orchestral texture",
    "Pizzicato orkestracija",
    "Polyphonic texture",
    "Register exploitation",
    "Sectional writing",
    "Solo vs. ensemble",
    "Sostenuto pedal effects",
    "Spatial effects",
    "String harmonics",
    "Timpani rolls",
    "Tremolo strings",

// 7. INSTRUMENTI
    "Alt saksofon",
    "Alt klarinet",
    "Bariton saksofon",
    "Bas klarinet",
    "Bas bubanj",
    "Basetni rog",
    "Engleski rog",
    "Eufonij",
    "Flexatone",
    "Flugelhorn",
    "Glockenspiel",
    "Harmonika",
    "Kastanjete",
    "Kontrafagot",
    "Kornet",
    "Lira",
    "Mandolina",
    "Piccolo flauta",
    "Sopran saksofon",
    "Tamburin",
    "Tamtam",
    "Tenor saksofon",
    "Tom-tom bubnjevi",
    "Tubular bells",
    "Wagnerian tuba",

// 8. GLAZBENI OBLICI
    "Cabaletta",
    "Character piece",
    "Concerto grosso",
    "Invention",
    "Motet",
    "Simfonijska pjesma",
    "Tone poem",

// 9. KOMPOZICIJA - tehnike
    "Augmentacija",
    "Basso continuo",
    "Cancrizans",
    "Chromatic mediant",
    "Common-tone modulation",
    "Contrary motion",
    "Cikličnost",
    "Diminucija",
    "Figured bass",
    "Ground bass",
    "Heterofonija",
    "Homoritmija",
    "Inverzija",
    "Monofonija",
    "Oblique motion",
    "Parallel motion",
    "Pivot chord",
    "Retrogradacija",
    "Retrograde inversion",
    "Similar motion",
    "Tonicization",
    "Unison writing",
    "Voice leading",

// 10. POLIFONIJA / KONTRAPUNKT
    "Anticipation",
    "Answer (fuge)",
    "Cambiata",
    "Countersubject",
    "Discantus",
    "Double fugue",
    "Episode",
    "Free entry",
    "Imitation at fifth",
    "Imitation at interval",
    "Imitation at octave",
    "Mensuration canon",
    "Mirror canon",
    "Neighbour tone",
    "Passing tone",
    "Pedal point",
    "Perpetual canon",
    "Real answer",
    "Regular entry",
    "Riddle canon",
    "Sinfonia (Bach)",
    "Species kontrapunkt",
    "Spiral canon",
    "Stretto fugue",
    "Stretto passage",
    "Suspension",
    "Tonal answer",
    "Triple fugue",
    "Voice crossing",
    "Voice exchange",
    "Échappée",

// 11. HARMONIJA

    "Borrowed chords",
    "Chord progression",
    "Kvintni krug",
    "Kvartni krug",
    "Deceptive cadence",
    "Drugi obrat",
    "Half cadence",
    "Harmonic rhythm",
    "Skrivene kvinte",
    "Skrivene oktave",
    "Imperfect cadence",
    "Modal interchange",
    "Napolitanski sekstakord",
    "Neopolitanski akord",
    "Njemački sekstakord",
    "Paralelne kvinte",
    "Paralelne oktave",
    "Savršena kadenca",
    "Frigijska kadenca",
    "Pikardijska terca",
    "Plagalna kadenca",
    "Povećani kvintsekstakord",
    "Povećani sekstakord",
    "Povećani sekundakord",
    "Mali smanjeni septakord",
    "Sekundarna dominanta",
    "Talijanski sekstakord",
    "Treći obrat",
    "Tritone substitution",
    "Undecimaakord",
    "Upper structure triads",
    "Pravilo vođenja glasova",

// 12. DIRIGIRANJE
    "Articulation indication",
    "Asymmetric meters",
    "Balans orkestar",
    "Bow direction",
    "Climax building",
    "Contemporary techniques",
    "Expressive gesture",
    "Historical performance",
    "Intonation correction",
    "Interpretative choice",
    "Metric modulation",
    "Mixed meters",
    "Phrasing gesture",
    "Rehearsal technique",
    "Score study",
    "Sectional rehearsal",
    "Senza misura",
    "Tension and release",
    "Unabhängigkeit (neovisnost ruku)",

// 13. ELEKTRONSKA GLAZBA
    "Acousmatic music",
    "Additive synthesis",
    "Amplitude modulation",
    "Attack",
    "Decay",
    "Electroacoustic",
    "Elektronska sinteza",
    "Filter (band-pass)",
    "Filter (high-pass)",
    "Filter (low-pass)",
    "FM synthesis",
    "Frequency modulation",
    "Granular synthesis",
    "LFO (low frequency oscillator)",
    "Live electronics",
    "Modular synthesis",
    "Multichannel audio",
    "Musique concrète",
    "Phase modulation",
    "Physical modeling",
    "Quadraphonic",
    "Release",
    "Resonance",
    "Ring modulation",
    "Spatialization",
    "Subtractive synthesis",
    "Sustain",
    "Tape music",
    "Voltage control",
    "Wavetable synthesis",

// 14. MUZIKOLOGIJA
    "Affektenlehre",
    "Akustika",
    "Autentični instrumenti",
    "Basso continuo realizacija",
    "Criticism (glazbena kritika)",
    "Diminution",
    "Equal temperament",
    "Hermeneutika",
    "Historically informed performance",
    "Improvizacija (historical)",
    "Just intonation",
    "Kognitivna muzikologija",
    "Meantone temperament",
    "Musica ficta",
    "Neumatska notacija",
    "Ornamentacija",
    "Performance studies",
    "Periodični instrumenti",
    "Pythagorean tuning",
    "Reception history",
    "Schenkerian analiza",
    "Socijalna muzikologija",
    "Temperament",
    "Well temperament",

// 16. OZNAKE DINAMIKE
    "Al niente",
    "Ben marcato",
    "Crescendo molto",
    "Diminuendo al niente",
    "Estinto",
    "Forte-fortissimo (ffff)",
    "Mezza voce",
    "Perdendosi",
    "Pianissimo possibile (ppp)",
    "Piano-pianissimo (pppp)",
    "Poco a poco crescendo",
    "Poco a poco diminuendo",
    "Quasi niente",
    "Sempre forte",
    "Sempre piano",

// 17. POVIJEST GLAZBE - razdoblja/stilovi
    "Aleatorika",
    "Ars subtilior",
    "Atonalnost",
    "Atonalitetnost",
    "Avangarda",
    "Dodekafonija",
    "Ekspresionizam",
    "Elektronička glazba",
    "Klaster",
    "Konkretna glazba",
    "Mikrotonalnost",
    "Minimalizam",
    "Neoklasicizam",
    "Neoromantizam",
    "Pointilizam",
    "Postminimalizam",
    "Postmodernizam",
    "Serializam",
    "Sonorizam",
    "Spektralna glazba"

];



// TEŠKO - Najspecijalističkiji pojmovi, rijetke tehnike
var klasicnaGlazbaTesko = [

// 1. SKLADATELJI
    "Arvo Pärt",
    "Claudio Monteverdi",
    "John Cage",
    "Karlheinz Stockhausen",
    "Olivier Messiaen",
    "Paul Hindemith",
    "Philip Glass",
    "Pierre Boulez",
    "Steve Reich",

// 2. OPERE
    "Ariadne auf Naxos",
    "Das Rheingold",
    "Der Freischütz",
    "Der Ring des Nibelungen",
    "Dido and Aeneas",
    "Jenůfa",
    "Lady Macbeth of Mtsensk",
    "Lulu",
    "Moses und Aron",
    "Peter Grimes",
    "Porgy and Bess",
    "Siegfried",
    "The Rake's Progress",
    "Wozzeck",

// 3. SOLFEGGIO
    "Akord",
    "Disonanca",
    "Modalni stupnjevi",
    "Modalni tetrakord",
    "Čista kvinta",

// 4. NOTNE VRIJEDNOSTI
    "Šezdesetčetvrtinka",
    "Šezdesetčetvrtinska pauza",

// 5. ARTIKULACIJE
    "Cirkularno disanje",
    "Multiphonics",

// 9. KOMPOZICIJA - tehnike
    "Modulation scheme",

// 10. POLIFONIJA / KONTRAPUNKT
    "Prva vrsta",
    "Crab canon",
    "Druga vrsta",
    "Peta vrsta",
    "Treća vrsta",
    "Četvrta vrsta",
    "Slobodni dvoglasni stavak",

// 11. HARMONIJA
    "Francuski sekstakord",
    "Sixte ajoutée",

// 14. MUZIKOLOGIJA
    "Glazbena teorija"

];

