// Psovke tema - riječi podijeljene po težini
// NAPOMENA: Psovke označene s /* DUPLIKAT */ ili /* SLIČNO */ su za pregled - obriši one koje ne želiš
// SVE KATEGORIJE SU SORTIRANE ABECEDNO

// LAGANO - jednostavne, benigne psovke i izražaji (ABECEDNO)
var psovkeRijeciLako = [
    "baksuz",
    "bedak",
    "boli me kurac",
    "budala",
    "budaletina",
    "budalo glupa",
    "debil",
    "dođavola",
    "drkadžija",
    "đubre",
    "gamad",
    "glupača",
    "glupan",
    "glupost",
    "govno jedno",
    "govno",
    "govnar",
    "govno smrdljivo",
    "idi do đavola",
    "idi do vraga",
    "do vraga",
    "idiot",
    "isuse bože",
    "jebi ga",
    "jebi se",
    "konj",
    "krava",
    "kravetina",
    "krele",
    "kreten",
    "kreten jedan",
    "kretenčina",
    "kurac",
    "kurva",
    "kurvetina",
    "kurvin sin",
    "ma daj molim te",
    "magarac",
    "magare",
    "majmun",
    "majmune jedan",
    "marva",
    "mazga",
    "mućko đubre",
    "mutav",
    "mutavko",
    "nitkov",
    "ne seri",
    "ovca",
    "panj",
    "peder",
    "pederčina",
    "pička",
    "propalica",
    "retard",
    "seljačina",
    "seljak",
    "seljober",
    "seronja",
    "smeće",
    "smrad",
    "sranje",
    "stoka",
    "stoko jedna",
    "šupak",
    "šupčina",
    "tele",
    "tupan",
    "tupson",
    "u pm",
    "u tri lepe",
    "vrag te odnesel",
    "vrag te odnio",
    "vrag ti pamet popil"
];

// SREDNJE - složenije psovke i fraze (ABECEDNO)
var psovkeRijeciSrednje = [
    "ajd u pičku materinu",
    "Allah te jebo",
    "bog ti mater jebi",
    "da bog da",
    "da ti bog dao",
    "drkam ti u usta",
    "grob te jebo",
    "grom te jebo",
    "idi u kurac",
    "idi u pičku materinu",
    "izjebat' ću te",
    "Irud te jebo",
    "Isus te jebo",
    "jebem li ti",
    "jebem ti",
    "jebem ti boga",
    "jebem ti familiju",
    "jebem ti krv",
    "jebem ti krv Isusovu",
    "jebem ti srce Isusovo",
    "jebem ti krv Irudovu",
    "jebem ti mater",
    "jebem ti sisu",
    "jebem ti sunce",
    "jebem ti sudbinu",
    "jebem ti sukrvicu",
    "jebem ti sve",
    "jebem ti sve po spisku",
    "jebem ti život",
    "jebeš me u zdrav mozak",
    "jebo te bobi",
    "jebo te bog",
    "jebo te grom",
    "jebo te pas",
    "jebo te Paško patak",
    "jebo te vrag",
    "jebo ti bog i sunce i mater",
    "jebo ti pas mater",
    "jebote",
    "jebote led",
    "jebote pas",
    "jebote život",
    "jebem ti život",
    "jedi govna",
    "jedi govna i umri",
    "koji ti je kurac",
    "krv ti jebem",
    "kučkin sin",
    "kurac od ovce",
    "kurvin sin",
    "kurvo prokleta",
    "majku ti jebem",
    "mater ti jebem",
    "najebat ćeš",
    "nosi se u pičku materinu",
    "oca ti jebem",
    "odi u tri pičke materine",
    "odjebi",
    "pas ti mater",
    "pička materina",
    "pička ti materina",
    "pičko jedna",
    "popuši mi",
    "puši kurac",
    "pušač kurca",
    "retardirani debil",
    "sisa",
    "sise",
    "sjebao si",
    "sjeb'o si",
    "smeće narkomansko",
    "sunce ti jebem",
    "u kurac s tim",
    "vrag te nosil",
    "vrag ti jebi mater",
    "vrag ti jebi sve",
    "vrag ti sriću odnia",
    "zajebancija",
    "zajebao si",
    "zajebavat"
];

// TEŠKO - hardcore i kreativne psovke (ABECEDNO)
var psovkeRijeciTesko = [
    "dabogda im'o pa nem'o",
    "dabogda ti crkla mater",
    "dabogda ti crk'o pas",
    "dabogda povratio",
    "dabogda te konj pregazio",
    "dabogda ti obrve izgorile",
    "dabogda dobio štucavicu",
    "dabogda prop'o u zemlju",
    "dabogda se otrov'o",
    "dabogda oćoravio",
    "dabogda krep'o",
    "dabogda se usr'o u gaće",
    "dabogda te majka rodila retardiranog",
    "dabogda ti se jezik otrgnuo",
    "dabogda ti se pas popišao po sred sobe",
    "dabogda ti se ruka osušila",
    "dabogda ti žena rodila ježića",
    "dabogda pukao od muke",
    "dabogda ti stara prdnula na roditeljskom",
    "dabogda ti žena prdnula na roditeljskom",
    "idi u kurac konjanika",
    "idi u pizdu materinu",
    "idi u šesnaest pizdi materinih",
    "idi ti u tri lepe pičke materine",
    "jebem ti boga",
    "jebem ti boga Isusa",
    "jebem ti boga na nebu",
    "jebem ti boga u pičku",
    "jebem ti celu rodbinu",
    "jebem ti crkvu",
    "jebem ti dan kad si rođen",
    "jebem ti dušu",
    "jebem ti Isusa",
    "jebem ti kola i kotače",
    "jebem ti kosti",
    "jebem ti krst",
    "jebem ti majku mrtvu",
    "jebem ti mater u pičku",
    "jebem ti miša u rupi",
    "jebem ti mleko materino",
    "jebem ti mrtvu majku",
    "jebem ti oca i majku",
    "jebem ti oca u zdrav mozak",
    "jebem ti onu stvar",
    "jebem ti pičku materinu",
    "jebem ti pleme i seme",
    "jebem ti pokoljenje",
    "jebem ti rod i porod",
    "jebem ti seme i pleme",
    "jebem ti sjeme i koljeno",
    "jebem ti sreću",
    "jebem ti sunce koje te prvi put obasjalo",
    "jebem ti sunce žarko",
    "jebem ti svece",
    "jebem ti sve po redu",
    "jebem ti sve po spisku do sedmog koljena",
    "jebem ti sve sveto",
    "jebem ti sve živo i mrtvo",
    "jebem ti tvoje i moje",
    "jebem ti zemlju gde si hodio",
    "jebem vam sve po spisku",
    "jebo bog tvoju mater",
    "jebo te deda u zdrav mozak",
    "jebo te tata u zdrav mozak",
    "jebo ti bog mater",
    "jebo ti isus mater",
    "jebo ti konj mater",
    "jebo ti kos u posan nos",
    "jebo ti more plisko",
    "jebo ti pas kosti",
    "jebo ti pas kostursku glavu",
    "jebo ti pas mater debelu",
    "jebo ti pas mater mrtvu",
    "jebo ti pas majku",
    "jebo ti pas oca",
    "jebo vas bog sve",
    "jedi govna na lopatu",
    "krv ti jebem po sred čela",
    "krv ti jebem prljavu",
    "kurvino kopile",
    "mrš u pičku materinu",
    "mrš u tri pičke materine",
    "nabijem te na kurac",
    "nabijem te na kurac do jaja",
    "nabijem ti kurac u usta",
    "pička ti materina raspala",
    "popij govno na slamku",
    "puši kurac i progutaj",
    "puši mi kurac",
    "serem ti se na grob",
    "serem ti se u usta",
    "serem ti se u život",
    "isprdim ti se u facu",
    "iserem ti se po faci",
    "poserem ti se u usta",
    "sunce ti jebem kalaisano",
    "sunce ti jebem žarko",
    "popišam ti se po grobu"
];
