// Seksualnost tema - riječi podijeljene po težini (sortirano po abecedi)

// LAGANO - osnovni pojmovi (sortirano)
var seksualnostRijeciLako = [
    "analni seks",
    "dildo",
    "drkadžija",
    "drkanje",
    "ejakulacija",
    "gel za podmazivanje",
    "guma",
    "jahanje",
    "jebanje",
    "karanje",
    "kita",
    "klitoris",
    "kondom",
    "kondomi",
    "kurac",
    "kurčenje",
    "kurčina",
    "kurvanje",
    "kurvarluk",
    "lizanje pičke",
    "lubrikant",
    "masturbacija",
    "masturbirati",
    "misionarska poza",
    "od pozadi",
    "oralni seks",
    "orgazam",
    "penetracija",
    "penis",
    "pička",
    "pilula",
    "pizda",
    "porno film",
    "pornić",
    "pornografija",
    "predigra",
    "pseća poza",
    "pušenje",
    "pušenje kurca",
    "reverse cowgirl",
    "sazada",
    "seks",
    "sjeme",
    "sperma",
    "svršavanje",
    "svršiti",
    "u šupak",
    "umjetni kurac",
    "vagina",
    "vibrator",
    "vrhunac",

    "abortirati",
    "bračna postelja",
    "bradavica",
    "dražica",
    "dojka",
    "erekcija",
    "glavić",
    "grupni sex",
    "grupnjak",
    "grudnjak",
    "halteri",
    "hemoroidi",
    "jajna stanica",
    "kurčić",
    "kurvati se",
    "lažni orgazam",
    "latex",
    "lutka na napuhavanje",
    "majčino mlijeko",
    "maternica",
    "mokraćni mjehur",
    "mokri snovi",
    "nekrofilija",
    "pedofilija",
    "pičkica",
    "poljubac",
    "požuda",
    "preljub",
    "preljubnik",
    "preljubnica",
    "rodnica",
    "samozadovoljavanje",
    "sida",
    "sifilis",
    "spolni organ",
    "stidna dlaka",
    "stidnica",
    "svirati kurcu",
    "šupak",
    "testisi",
    "umjetna oplodnja"
];

// SREDNJE - specifičnije prakse (sortirano)
var seksualnostRijeciSrednje = [
    "analna kuglica",
    "bič",
    "cetvorka",
    "čep za šupak",
    "dominacija",
    "dominantni partner",
    "dvostruka penetracija",
    "duboko grlo",
    "duboko pušenje",
    "fetish stopala",
    "fisting",
    "foot fetish",
    "G točka",
    "grupnjak",
    "gutanje sperme",
    "jebanje sisa",
    "kneblo u ustima",
    "kneblovanje",
    "lanac",
    "lisice",
    "lizanje šupka",
    "mokraća",
    "obostrano lizanje",
    "orgija",
    "palica za udaranje",
    "pišanje",
    "prskanje",
    "prostata",
    "razmjena partnera",
    "rimming",
    "robovanje",
    "seks u autu",
    "sise jebanje",
    "stimulacija klitorisa",
    "strapon",
    "submisivni partner",
    "swingeri",
    "svršavanje na lice",
    "svršavanje na sise",
    "svršavanje u usta",
    "šaka u pički",
    "šaka u šupku",
    "šezdeset i devet",
    "šibanje",
    "trojka",
    "trokut",
    "u oba otvora",
    "udaranje po guzici",
    "umjetni kurac na pojasu",
    "vezivanje",
    "zlatni tuš",
    "žensko svršavanje",

    "analni umetak",
    "edipov kompleks",
    "elektrin kompleks",
    "erektilna disfunkcija",
    "hemofilija",
    "hepatitis",
    "hepatitis B",
    "hepatitis C",
    "isprdak",
    "jebanje majki",
    "jebežljiv",
    "ljubavni ugriz",
    "masaža prostate",
    "nakurnjak",
    "orgazmičko iskustvo",
    "pičkin dim",
    "potrošeni kondom",
    "prcati",
    "predejakulacija",
    "seksualni poremećaj",
    "sjemenovod",
    "smegma",
    "spermatozoid",
    "spirala",
    "spolovilo",
    "spolna bolest",
    "spontani pobačaj",
    "sretan završetak",
    "stidne usne",
    "svršavanje po faci",
    "swingerski par",
    "tantrički seks",
    "tantra",
    "vaginalni iscjedak",
    "zguza"
];

// TEŠKO - hardcore termini (sortirano)
var seksualnostRijeciTesko = [
    "analni lančić",
    "autoerotično gušenje",
    "bez kondoma",
    "bolno analno",
    "cruising",
    "daljinski vibrator",
    "električna stimulacija",
    "električni štapić",
    "elektro seks",
    "elektro torture",
    "erotsko gušenje",
    "grgljanje sperme",
    "grupno svršavanje",
    "gušenje za uzbuđenje",
    "igra s noževima",
    "iz guzice u usta",
    "iz šupka u usta",
    "japansko vezivanje",
    "javni seks",
    "kavez čednosti",
    "kineske kuglice",
    "krv i seks",
    "krvava igra",
    "mučenje jaja",
    "napuhavajući čep",
    "nezaštićeni seks",
    "noževi i seks",
    "prebacivanje sperme",
    "prisilni orgazam",
    "prisilno uzdravanje",
    "prsten za kurac",
    "pumpanje kurca",
    "rastezanje kurca",
    "rupa slave / glory hole",
    "ruski rulet seksa",
    "samolizaj",
    "samopušenje",
    "seks mašina",
    "silovit analni seks",
    "suspenzija vezanja",
    "stroj za jebanje",
    "svršavanje na lice grupe",
    "traženje seksa parkovima",
    "udaranje testisa",
    "umjetnost vezivanja",
    "uskraćivanje orgazma",
    "vakuum pumpa",
    "viseće vezivanje",

    "analne radosti",
    "bukkake",
    "dojka djevojačka",
    "gnojni iscjedak",
    "izdrkotina",
    "kurcobolja",
    "onanija",
    "oplođena jajna stanica",
    "preživjeli abortus",
    "rasplodna krmača"
];
