// Sport tema - riječi podijeljene po težini

// LAGANO - osnovni sportovi i pojmovi
var sportRijeciLako = [
    "nogomet",
    "košarka",
    "tenis",
    "odbojka",
    "rukomet",
    "golf",
    "hokej",
    "atletika",
    "plivanje",
    "skijanje",
    "boks",
    "gimnastika",
    "trčanje",
    "biciklizam",
    "fitnes",
    "gol",
    "lopta",
    "trener",
    "sudac",
    "medalja",
    "zlato",
    "srebro",
    "bronca"
];

// SREDNJE - specifičniji sportovi i termini
var sportRijeciSrednje = [
    "vaterpolo",
    "snowboard",
    "hrvanje",
    "judo",
    "karate",
    "taekwondo",
    "triatlon",
    "maraton",
    "sprint",
    "skok u dalj",
    "skok u vis",
    "bacanje koplja",
    "bacanje diska",
    "ragbi",
    "američki nogomet",
    "baseball",
    "kriket",
    "badminton",
    "stolni tenis",
    "squash",
    "streličarstvo",
    "jahanje",
    "jedrenje",
    "veslanje",
    "surfanje",
    "ronjenje",
    "bilijar",
    "kuglanje",
    "šah",
    "pikado",
    "dizanje utega",
    "planinarenje",
    "penjanje",
    "padobranstvo",
    "ski skokovi",
    "alpsko skijanje",
    "nordijsko skijanje",
    "biatlon",
    "curling",
    "klizanje",
    "hokej na ledu",
    "Formula 1",
    "MotoGP",
    "golman",
    "braniš",
    "napadač",
    "finale",
    "turnir",
    "liga",
    "prvenstvo"
];

// TEŠKO - specifični termini, pozicije, turniri
var sportRijeciTesko = [
    "kugla",
    "vijača",
    "motka",
    "košarkaški koš",
    "hat-trick",
    "penal",
    "korner",
    "aut",
    "slobodno bacanje",
    "trojka",
    "zakucavanje",
    "servis",
    "volej",
    "smeč",
    "blok",
    "igra u obrani",
    "igra u napadu",
    "kapetan",
    "vezni",
    "krilo",
    "pivot",
    "centar",
    "bekovi",
    "plej-off",
    "polufinale",
    "četvrtfinale",
    "kup",
    "olimpijske igre",
    "svjetsko prvenstvo",
    "europsko prvenstvo",
    "rekord",
    "dopiranje",
    "fairplay",
    "reli",
    "konjičke trke",
    "greyhound utrke",
    "pomoćni sudac"
];
